services:
  website:
    container_name: hom-website
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./app.db:/app/app.db:rw
      - ./media:/app/media:rw
      - ./logs:/app/logs:rw
    environment:
      # Change this to your domain
      - ORIGIN=https://hootormeow.hootsifer.com
    env_file:
      - .env
    networks:
      - nginx

networks:
  nginx:
    external: true
    name: nginx
